SELECT 
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS "TOTAL_DISTANCE",
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS "AVERAGE_DISTANCE"
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC; -- (별칭 대신 원본 값으로 정렬하는 것이 더 안전합니다)