-- 코드를 작성해주세요

SELECT b.QUA AS "QUARTER", COUNT(a.ID) AS "ECOLI_COUNT"
FROM ECOLI_DATA a
JOIN (SELECT 
CASE
    WHEN MONTH(DIFFERENTIATION_DATE) >= 1 AND MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) >= 4 AND MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) >= 7 AND MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
    WHEN MONTH(DIFFERENTIATION_DATE) >= 10 AND MONTH(DIFFERENTIATION_DATE) <= 12 THEN '4Q'
END AS QUA,
ID AS ID
FROM ECOLI_DATA) b ON a.ID = b.ID
GROUP BY b.QUA
ORDER BY QUARTER ASC;