SELECT DISTINCT d.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO a
JOIN (
    SELECT b.ITEM_ID AS "ITEM_ID"
    FROM ITEM_TREE b
    JOIN ITEM_INFO c ON c.RARITY = 'RARE' AND c.ITEM_ID = b.PARENT_ITEM_ID
) d ON d.ITEM_ID = a.ITEM_ID
ORDER BY d.ITEM_ID DESC;