-- 코드를 작성해주세요
SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
JOIN (
    SELECT DISTINCT CODE AS "SELECT_CODE"
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
     ) s ON d.SKILL_CODE & s.SELECT_CODE = s.SELECT_CODE
ORDER BY d.ID ASC;