SELECT 
    YEAR(a.DIFFERENTIATION_DATE) AS YEAR,
    b.MAX_SIZE_OF_YEAR - a.SIZE_OF_COLONY AS YEAR_DEV,
    a.ID
FROM 
    ECOLI_DATA a
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS year_col, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) b 
  ON YEAR(a.DIFFERENTIATION_DATE) = b.year_col
ORDER BY 
    YEAR ASC, YEAR_DEV ASC;