WITH RankedFish AS (
    SELECT f.ID, n.FISH_NAME, f.LENGTH, RANK() OVER (PARTITION BY f.FISH_TYPE ORDER BY LENGTH DESC) AS "RNK"
    FROM FISH_INFO f
    JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM RankedFish
WHERE RNK = 1
ORDER BY ID ASC;